---
version: "3.7"
services:
  web:
    image: nginx:alpine
    volumes:
      - type: bind
        source: ./generator
        target: /opt/app/generator
      - type: bind
        source: ./resources
        target: /opt/app/resources
      - type: bind
        source: ./config/nginx.conf
        target: /etc/nginx/conf.d/default.conf
    ports:
      - target: 80
        published: 8080
        protocol: tcp
        mode: host
  dev:
    build:
      context: 'resources/tools'
    volumes:
      - type: bind
        source: ./generator
        target: /opt/app/generator
      - type: bind
        source: ./resources
        target: /opt/app/resources
    entrypoint: 
      - tail 
      - -f 
      - /dev/null